### PR TITLE
Change std.build.Pkg.path to std.build.Pkg.source

### PR DESCRIPTION
**Pull request by kamidev**
Fix breaking change in Zig master, see https://github.com/ziglang/zig/pull/11557

- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Review by alichraghi — APPROVED** [review]

**Review by iddev5 — CHANGES_REQUESTED** [review]
Mach still uses an old version of zig in it's CI. That has to be updated first.

**Comment by kamidev** [comment]
> Mach still uses an old version of zig in it's CI. That has to be updated first.

Of course. Do you want me to leave this open until then?

**Comment by iddev5** [comment]
Yeah just keep it open, it's all ready apart from that.

**Comment by slimsag** [comment]
Thanks for sending! I'll merge this weekend!

**Comment by slimsag** [comment]
Merging, this will temporarily break `main` but I'll update our CI in the next few hours.

**Pull request merged**
