### PR TITLE
gpu: beginnings of Dawn WebGPU backend

### PR DESCRIPTION
**Pull request by slimsag**
What works:

* https://github.com/hexops/dawn is a fork of Google's Dawn which will track upstream closely, only difference is it has generated code committed so we do not require installation of `depot_tools`, `ninja`, `make`, `gn`, etc. tools that Google requires.
* `build.zig` builds all of Dawn using only the Zig compiler, currently only working on MacOS but should be easy to get building on other targets soon. Depends on PR I sent ziglang/zig#10096 to enable Zig to compile Obj-C++ code.
* `webgpu/src/dawn` contains C shims for all the dawn_native functionality which is required to get Dawn actually attached to a window / set up.
* `cd webgpu && zig build run-dawn-example` shows it all working:

This PR does not enable cross-compilation of Dawn. It does not add Zig WebGPU wrappers. These will come later.

- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Comment by slimsag** [comment]
Instructions for trying this on macOS:

#### 1. Clone the repo, switch to this branch and clone submodules

```
git clone https://github.com/hexops/mach
cd mach/
git checkout dawn
git submodule update --init --recursive
```

#### 2. Run the example

```
cd webgpu/
zig build run-dawn-example
```

Compilation is a bit slow, be prepared to wait for ~5m or so.

**Comment by silversquirl** [comment]
Are you sure this works from a clean state? The vulkan-deps submodule is full of (almost) empty subdirs, so I'm wondering whether you might have some cached files from a depot_tools build in yours.
```
$ ls vulkan-deps/*
vulkan-deps/DEPS     vulkan-deps/README.chromium               vulkan-deps/update-commit-message.py
vulkan-deps/LICENSE  vulkan-deps/README.md
vulkan-deps/OWNERS   vulkan-deps/additional_readme_paths.json

vulkan-deps/glslang:
DIR_METADATA  LICENSE  README.chromium

vulkan-deps/spirv-cross:
DIR_METADATA  README.chromium

vulkan-deps/spirv-headers:
DIR_METADATA  LICENSE  README.chromium

vulkan-deps/spirv-tools:
DIR_METADATA  LICENSE  README.chromium

vulkan-deps/vulkan-headers:
DIR_METADATA  LICENSE.txt  README.chromium

vulkan-deps/vulkan-loader:
README.chromium

vulkan-deps/vulkan-tools:
README.chromium

vulkan-deps/vulkan-validation-layers:
README.chromium
```
The vulkan-deps gitignore seems to ignore all the sources. It doesn't use git submodules, so presumably the build system fetches them:
```
$ cat vulkan-deps/.gitignore
DEPS.old
/glslang/src
/spirv-cross/src
/spirv-headers/src
/spirv-tools/src
/vulkan-headers/src
/vulkan-loader/src
/vulkan-tools/src
/vulkan-validation-layers/src
```

**Comment by slimsag** [comment]
Sorry about that @silversquirl - you're right, I'm still sorting out that exact issue. I was going to give you a ping once I sorted that out but I might need another day :)

**Comment by slimsag** [comment]
@silversquirl with the commits I just pushed, the instructions above should work now.

While building this all from source is cool, I also just want to say this isn't the dev experience I want. Dealing with all the submodule hell, and the slow C++ compilation times are not acceptable IMO and I'll be working on ways to fix this out-of-the-box (maybe having build-from-source be an option, with build-from-binary being the default)

**Comment by slimsag** [comment]
I've simplified the submodule situation a lot. Instead of converting `gclient` repositories (where are actual repositories) into Git submodules in our fork of Dawn https://github.com/hexops/dawn I have instead committed all dependencies / sub-repositories of that one directly to that repository.

This means that aside from this repository including https://github.com/hexops/dawn as a Git submodule, there is not any other submodule madness to deal with. The build instructions are now just:

```
git clone -b dawn --recursive https://github.com/hexops/mach
cd mach/webgpu
zig build run-dawn-example
```

**Comment by slimsag** [comment]
Merging, but this only works on MacOS right now. More PRs coming very soon to enable this to work on other OS, with cross compilation, and an idiomatic Zig interface over WebGPU's API.

**Pull request merged**
