### PR TITLE
enumify: make all constants proper ziggified enums

### PR DESCRIPTION
**Pull request by slimsag**
This makes all GLFW constants proper Zig enums, fixing hexops/mach#37

Also fixes some previously failing tests that were not included properly, and moves e.g. `glfw.mod.Mod` to `glfw.Mod`

- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Comment by slimsag** [comment]
@Avokadoen FYI this is a fairly large change, things are much nicer now but depending on how extensive your usage is you may need to update a bit. Hope that's okay :)

**Comment by Avokadoen** [comment]
@slimsag Awesome work! 🥳 
I'm still locked to my old fork for now. Having issue with vulkan in master branch. I haven't filed a issue since I am unsure exactly what is wrong, but it _seems_ the upstream vulkan files and my system vulkan library is two different versions and it causes issues when i try to call ``glfw.createWindowSurface`` (get error -7). 🤔

**Comment by slimsag** [comment]
@Avokadoen I'm not sure what -7 corresponds to, but you might be running into an issue I fixed just last night in https://github.com/hexops/mach/commit/c16d6bf615df5403244ad93fc6f6ee2adc4f7bf3

Also, I just published an example to confirm mach-glfw and vulkan-zig work well together, check it out: https://github.com/hexops/mach-glfw-vulkan-example

**Comment by Avokadoen** [comment]
Awesome, I'll try to update asap! 😍

**Pull request merged**
