### PR TITLE
gpu: add glfw dependency to example and fix issue

### PR DESCRIPTION
**Pull request by rudedogg**
I noticed the triangle example in `libs/gpu` stopped working (ran with `zig build run-example`).

It looks like https://github.com/hexops/mach/commit/a52c6e5f5c92ae0f83f919dd6fd088db0dce34db accidentally removed glfw from `libs/gpu/build.zig` and `libs/gpu/sdk.zig`. I could be missing something, but re-adding the dependency got the `libs/gpu` example building again.

One other issue was the change to Dawn that requires the next chain to be null needed handled. I blindly copied the change discussed here:  https://github.com/hexops/mach/pull/672#pullrequestreview-1248810820

- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Comment by rudedogg** [comment]
Shoot, looks like this fixes the gpu example but breaks other stuff.

**Comment by alichraghi** [comment]
@rudedogg glfw linkage isn't accidentally removed from `libs/gpu/sdk.zig`. i think the proper fix is linking glfw directly to `gpu` (not `gpu-dawn`) with `glfw.link(b, example, .{})`

**Comment by rudedogg** [comment]
> @rudedogg glfw linkage isn't accidentally removed from `libs/gpu/sdk.zig`. i think the proper fix is linking glfw directly to `gpu` (not `gpu-dawn`) with `glfw.link(b, example, .{})`

Ah I see. Thanks!

I force-pushed the fix you suggested, now mach itself builds, and the gpu example triangle still works. 

Let me know if anything else needs changed.

**Review by alichraghi — APPROVED** [review]

**Review by slimsag — APPROVED** [review]
Thank you!

**Pull request merged**
