### PR TITLE
{freetype,sysaudio}: use `std.refAllDeclsRecursive`

### PR DESCRIPTION
**Pull request by alichraghi**
added to stdlib via https://github.com/ziglang/zig/pull/12103

- [X] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Comment by alichraghi** [comment]
i wonder why CI uses old zig. i just downloaded and it include my PR

**Comment by iddev5** [comment]
CI doesn't follows zig master. The version is hard coded.

**Comment by slimsag** [comment]
You just need to run:

```sh
ZIG_VERSION=0.10.0-dev.3027+0e26c6149 ./dev/update-zig.sh
```

It'll do all the work of updating hard-coded locations for you. Just commit the result with message like `all: update to Zig version 0.10.0-dev.3027+0e26c6149`

**Comment by slimsag** [comment]
CI version updated, so this _should_ be good to go I think. I'll merge and we'll fix CI later by updating version again if needed.

**Review by slimsag — APPROVED** [review]

**Pull request merged**
