### PR TITLE
Fixed ErrorCallback.init() alignment

### PR DESCRIPTION
**Pull request by PiergiorgioZagaria**
- [X] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Comment by slimsag** [comment]
@PiergiorgioZagaria do you mind updating all locations with a bulk find-and-replace in your editor? Fine to do it in this PR. Shouldn't be too hard, no need to test each one or anything. Seems like there are a lot of locations we need to update:

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/hexops/mach%24+callback%28if+%28Context+%3D%3D+void%29&patternType=literal

**Comment by PiergiorgioZagaria** [comment]
Oh I didn't think about that, will do it right now

**Comment by PiergiorgioZagaria** [comment]
I checked and there are more parts where it appears,
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/hexops/mach%24+%40ptrCast%28Context%2C+%40alignCast%28%40alignOf%28Context%29&patternType=literal

**Comment by PiergiorgioZagaria** [comment]
Plus some more that don't use context but also ptrCast(pointer, alignCast(alignOf(Pointer

**Comment by slimsag** [comment]
Good catch, I think we only need to do it in `Callback` struct types' init methods.

A find and replace for `@ptrCast(Context, @alignCast(@alignOf(Context)` should be good enough I think.

(unrelated, looks like some of these locations need to be updated with `if (Context == void) {} else @ptrCast` too for consistency / `void` context support.)

**Review by slimsag — APPROVED** [review]
Looks great, thanks so much again!

**Comment by PiergiorgioZagaria** [comment]
No prob

**Pull request merged**
