### PR TITLE
known-issues: add a solution to the `Windows: File not found` problem

### PR DESCRIPTION
**Pull request by C-BJ**
- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Comment by slimsag** [comment]
It's not clear to me what you are fixing here.

The instructions here already say as the last step: `Re-clone the repository and try again.` - did you run into an issue doing that?

**Comment by slimsag** [comment]
Apologies but this change doesn't make sense to me. Please open an issue if you run into this and I can help / figure out how to update these docs. As it stands, I think this would confuse others.

> didn't download the git submodules, since dawn and DirectXShaderCompiler are removed from the source tree, the problem can be solved by recursively clone

These submodules are not needed. Cloning recursively will not help with cloning them either, as they are not submodules anymore.

**Comment by C-BJ** [comment]
I know that `git clone --recursive` do not clone dawn and DirectXShaderCompiler, `git clone --recursive` just clone the submodules like glfw.

**Comment by C-BJ** [comment]
since dawn and DirectXShaderCompiler are removed from the source tree, `git clone --recursive` will not clone them, so we can use `git clone --recursive` to clone the submodules we need, so the issue in doc should be fixed

**Comment by C-BJ** [comment]
@slimsag

**Pull request closed without merging**
