### PR TITLE
Update to Zig master

### PR DESCRIPTION
**Pull request by leecannon**
- `std.math.ceil` has been removed https://github.com/ziglang/zig/commit/41dd2beaacade94c5c98400a4a655aea07b9e2f3
- `std.ChildProcess.init` does not allocate anymore https://github.com/ziglang/zig/commit/a0a2ce92ca129d28e22c63f7bace1672c43776b5

- [X] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Comment by iddev5** [comment]
1) zigimg has not yet been updated from upstream
2) zig version has to be changed in CI for this change to work

**Comment by leecannon** [comment]
1. I've submitted a PR to zigimg: https://github.com/zigimg/zigimg/pull/67
2. Updated the CI

Maybe it's worth switching to https://github.com/marketplace/actions/setup-zig, easy as:
```yaml
- uses: goto-bus-stop/setup-zig@v1
  with:
    version: master
```

**Comment by iddev5** [comment]
I dont have any evidence, but I think pinning zig to a particular version was intentional.

**Review by iddev5 — APPROVED** [review]

**Comment by iddev5** [comment]
CI fail reason: https://github.com/hexops/mach/blob/68d167993145a9c1d5998129e2c37c02db2bac8a/.github/workflows/ci.yml#L60

**Comment by slimsag** [comment]
Do you mind doing a find+replace of `0.10.0-dev.1600+af844931b` -> `0.10.0-dev.2017+a0a2ce92c` across the entire repo? There are other subrepos that have their own GitHub action CI pipelines, and I need to keep them all in sync.

Will give https://github.com/zigimg/zigimg/pull/67 a day ish to land and then merge this so we don't break the examples (or if you want to update the submodule to point to your fork temporarily, that'd work too)

**Comment by leecannon** [comment]
Find replace done.

**Comment by slimsag** [comment]
Switched temporarily to a fork of zigimg until that PR is merged.

**Review by slimsag — APPROVED** [review]
Thanks a ton for this!

**Pull request merged**
